# Generated by Django 4.2.22 on 2025-10-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='organisation',
        ),
    ]
