# Generated by Django 4.2.22 on 2025-10-05 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_remove_jobdescription_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('training_type', models.CharField(blank=True, max_length=150, null=True)),
                ('date_conducted', models.DateField(default=django.utils.timezone.now)),
                ('effectiveness', models.TextField(blank=True, help_text='Assessment of training effectiveness', null=True)),
                ('trainer', models.CharField(blank=True, max_length=150, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/training_records/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training Record',
                'verbose_name_plural': 'Training Records',
                'ordering': ['-date_conducted'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('people', 'People'), ('equipment', 'Equipment'), ('IT', 'IT Systems'), ('facility', 'Facility'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('planned_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('provided', 'Provided'), ('reviewed', 'Reviewed')], default='planned', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/resource_plans/')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Plan',
                'verbose_name_plural': 'Resource Plans',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=150, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='qms/document_registers/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Register',
                'verbose_name_plural': 'Document Registers',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audience', models.TextField(help_text='Target audience')),
                ('method', models.CharField(max_length=150)),
                ('frequency', models.CharField(blank=True, help_text='e.g., Weekly, Monthly', max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/communication_plans/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Plan',
                'verbose_name_plural': 'Communication Plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AwarenessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_audience', models.TextField(help_text='Who received the communication')),
                ('method', models.CharField(help_text='e.g., Meeting, Email, Poster, Training', max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/awareness_records/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('communicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awareness_communicated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Awareness Record',
                'verbose_name_plural': 'Awareness Records',
                'ordering': ['-date'],
            },
        ),
    ]
