# Generated by Django 4.2.22 on 2025-10-05 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0004_awarenessrecord_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('technical', 'Technical'), ('QA', 'Quality Assurance')], max_length=150)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Design Project',
                'verbose_name_plural': 'Design Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('evaluation_result', models.TextField(blank=True, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/supplier_evaluations/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_suppliers', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
            ],
            options={
                'verbose_name': 'Supplier Evaluation',
                'verbose_name_plural': 'Supplier Evaluations',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('operations', 'Operations'), ('QA', 'Quality Assurance')], max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='qms/sops/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sops', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('compliance_with_requirements', models.BooleanField(default=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/service_reports/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Report',
                'verbose_name_plural': 'Service Reports',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/product_approvals/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_approvals', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
            ],
            options={
                'verbose_name': 'Product Release',
                'verbose_name_plural': 'Product Releases',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='NCRRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('QA', 'QA'), ('Operations', 'Operations')], default='QA', max_length=150)),
                ('description', models.TextField()),
                ('detected_date', models.DateField(default=django.utils.timezone.now)),
                ('corrective_action_taken', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=50)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/ncr/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nonconforming Output',
                'verbose_name_plural': 'NCR Register',
                'ordering': ['-detected_date'],
            },
        ),
        migrations.CreateModel(
            name='DesignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('plan', 'Plan'), ('review', 'Review'), ('verification', 'Verification'), ('validation', 'Validation'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_file', models.FileField(upload_to='qms/design_records/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_design_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='system.designproject')),
            ],
            options={
                'verbose_name': 'Design Record',
                'verbose_name_plural': 'Design Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(choices=[('sales', 'Sales'), ('QA', 'Quality Assurance')], max_length=150)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('findings', models.TextField(blank=True, null=True)),
                ('document_reference', models.FileField(blank=True, null=True, upload_to='qms/contract_reviews/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Review',
                'verbose_name_plural': 'Contract Reviews',
                'ordering': ['-review_date'],
            },
        ),
    ]
